### ISSUE TITLE
Gradebook

### ISSUE THREAD

**Issue by MarijaBircevic** [alptium/marija.bircevic#5]

**Comment by MarijaBircevic** [comment]
Done

**Comment by valentinajemuovic** [comment]
@MarijaBircevic, see my comments on #3 and https://github.com/alptium/valentina.cupac/wiki/03.-Hello-World

**Comment by valentinajemuovic** [comment]
@MarijaBircevic: https://github.com/alptium/valentina.cupac/wiki/03.-Hello-World see 29, 15, 30, 31, 32, 23.

**Comment by valentinajemuovic** [comment]
@MarijaBircevic 
29: Not fixed
15: Ok
30: Ok
31: Not fixed
32: Not fixed
23: Ok
14: Fix this too

Let me know if the comments are clear, or we can review during a meeting.

**Comment by valentinajemuovic** [comment]
@MarijaBircevic, correct.
